channels:
  - conda-forge
dependencies:
  - conda-forge::numba
  - conda-forge::nutpie
  - conda-forge::python>=3.12.8
  - conda-forge::pytensor
  - libblas=*=*accelerate
  - conda-forge::conda
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::pandas
  - conda-forge::ipykernel
  - conda-forge::jax
  - conda-forge::blackjax
  - conda-forge::arviz
  - conda-forge::pip
  - conda-forge::ipywidgets
  - conda-forge::numpyro
  - conda-forge::numpy
  - conda-forge::polars
  - conda-forge::pymc>=5.19
  - conda-forge::statsmodels
  - conda-forge::nibabel
  - conda-forge::nilearn
  - conda-forge::bambi
  - conda-forge::cloudpathlib
  - conda-forge::tqdm
  - conda-forge::templateflow
  - conda-forge::nutpie
  - conda-forge::pyarrow
  - conda-forge::pytest
  - pip:
    - bayeux-ml
    - nbconvert



